export const ADD_AUTO_LOGIN = 'ADD_AUTO_LOGIN';
export const REMOVE_AUTO_LOGIN = 'REMOVE_AUTO_LOGIN';
export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';
export const CHANGE_FIRST_TIME_STATUS = 'CHANGE_FIRST_TIME_STATUS';
